try this

diff --git a/.github/workflows/benchmarking-workflow.yml b/.github/workflows/benchmarking-workflow.yml
--- a/.github/workflows/benchmarking-workflow.yml
+++ b/.github/workflows/benchmarking-workflow.yml
@@ -1,8 +1,11 @@
-# name: Validate SPDX License year and company mention in currently changed Files
+# name: Check SPDX Licenses
 
 # on:
+#   workflow_dispatch:
+#   workflow_call:
 #   pull_request:
-#     branches: [main]
+#     branches:
+#       - "main"
 #     types:
 #       - opened
 #       - reopened
@@ -11,74 +14,58 @@
 #       - review_requested
 
 # jobs:
-#   check-spdx-license:
-#     runs-on: ubuntu-latest
+#   check-spdx-licenses:
+#     runs-on: ubuntu-20.04
 #     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v4
+#       - uses: actions/checkout@v4
+#       - uses: actions/setup-python@v5.0.0
 #         with:
-#           fetch-depth: 0
-
-#       - name: Set up ignored files
+#           cache: "pip"
+#           python-version: "3.8"
+#       - name: Install copyright check tool
+#         run: pip install git+https://github.com/espressif/check-copyright.git@master
+#       - name: Check SPDX licenses
+#         id: check_spdx_licenses
 #         run: |
-#           # Define ignored files as a multi-line string
-#           echo "ignored_files=\
-#           file1.py \
-#           file2.py" >> $GITHUB_ENV
-
-#       - name: Identify currently changed files and check licenses
-#         id: check-licenses
+#           set +e
+#           output=$(python -m check_copyright --verbose --dry-run --config ./check_copyright_config.yaml . 2>&1)
+#           exit_code=$?
+#           clean_output=$(echo "$output" | sed 's/\x1b\[[0-9;]*m//g')
+#           echo "$clean_output"
+#           echo "CLEAN_OUTPUT<<EOF" >> $GITHUB_ENV
+#           echo "$clean_output" >> $GITHUB_ENV
+#           echo "EOF" >> $GITHUB_ENV
+#           echo "EXIT_CODE=$exit_code" >> $GITHUB_ENV
+#           exit 0
+#       - name: Extract Files
+#         id: extract_files
 #         run: |
-#           current_year=$(date +"%Y")  # Dynamically set current year for checking
-#           echo "current_year=$current_year" >> $GITHUB_ENV  # Export current year to environment variables
-#           ignored_files=($ignored_files)  # Convert ignored files string to array
-#           missing_license_files=""
-#           echo "Checking for license compliance..."
-#           for file in $(git diff --name-only HEAD^ HEAD | grep '\.py$'); do
-#             if [[ ! " ${ignored_files[@]} " =~ " ${file} " ]]; then  # Check if file is not in the ignored list
-#               # Check if file contains the correct SPDX license identifier and the exact copyright statement with dynamic current year
-#               if ! grep -q "SPDX-License-Identifier: Apache-2.0" "$file"; then
-#                 echo "File $file is missing SPDX-License-Identifier."
-#                 missing_license_files="$missing_license_files$file "
-#               elif ! grep -q "SPDX-FileCopyrightText: © $current_year Tenstorrent AI ULC" "$file"; then
-#                 echo "File $file is missing or has incorrect SPDX-FileCopyrightText."
-#                 missing_license_files="$missing_license_files$file "
-#               else
-#                 echo "File $file passed license check."
-#               fi
-#             else
-#               echo "File $file is ignored."
-#             fi
-#           done
-#           if [[ -z "$missing_license_files" ]]; then
-#             echo "All files passed the license check."
-#           else
-#             echo "missing_license_files=$missing_license_files" >> $GITHUB_ENV
-#             echo "Some files failed the license check."
-#           fi
-#           echo "License compliance check completed."
-
-#       - name: Comment on PR about incorrect SPDX licenses
-#         if: env.missing_license_files != ''
+#           files=$(echo "${{ env.CLEAN_OUTPUT }}" | awk '/Files which failed the copyright check:/,/Additional information about this hook and copyright headers may be found here:/' | sed '1d;$d')
+#           echo "FILES<<EOF" >> $GITHUB_ENV
+#           echo "$files" >> $GITHUB_ENV
+#           echo "EOF" >> $GITHUB_ENV
+#       - name: Debug Extracted Files
+#         run: |
+#           echo "Extracted Files:"
+#           echo "${{ env.FILES }}"
+#       - name: Post GitHub Comment
 #         uses: actions/github-script@v6
 #         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
 #           script: |
-#             const issueNumber = context.issue.number;
-#             const owner = context.repo.owner;
-#             const repo = context.repo.repo;
-#             const missingFiles = process.env.missing_license_files.trim().replace(/\s+/g, '\n');
-#             const currentYear = process.env.current_year;
-#             const commentBody = `The following files are not compliant with the required licensing standards for ${currentYear} or do not contain the correct copyright text 'Tenstorrent AI ULC' within their license header:\n\`\`\`\n${missingFiles}\n\`\`\`\nPlease update the files accordingly. Your attention and cooperation in this matter are greatly appreciated.\nThank you.`;
-
-#             github.rest.issues.createComment({
-#               issue_number: issueNumber,
-#               owner: owner,
-#               repo: repo,
-#               body: commentBody
-#             });
-
-#       - name: Fail the workflow if license issues are found
-#         if: env.missing_license_files != ''
-#         run: |
-#           echo "Failing the workflow due to non-compliance with SPDX license requirements."
-#           exit 1
+#             const files = process.env.FILES;
+#             if (files) {
+#               const issueNumber = context.payload.pull_request.number;
+#               const owner = context.repo.owner;
+#               const repo = context.repo.repo;
+#               const commentBody = `Our automated SPDX license verification process has discovered that the following files are missing a license header:\n\`\`\`\n${files}\n\`\`\`\nPlease ensure each indicated file includes a valid SPDX license identifier. This is essential for maintaining licensing compliance. Your attention and cooperation in updating these files are greatly appreciated. Thank you.`;
+#               await github.rest.issues.createComment({
+#                 issue_number: issueNumber,
+#                 owner: owner,
+#                 repo: repo,
+#                 body: commentBody
+#               });
+#               core.setFailed("SPDX license issues found.");
+#             } else {
+#               console.log("No SPDX license issues found.");
+#             }
